### ISSUE TITLE
[FEATURE] Enhance CCR to support primary cluster response and shadow clusters

### ISSUE THREAD

**Issue by kartg** [opensearch-project/opensearch-migrations#100]
This issue is to track the idea proposed by @nknize here - https://github.com/opensearch-project/opensearch-migrations/issues/91#issuecomment-1411065198

CCR has an ongoing iterative effort to [redesign large components leveraging SegRep](https://github.com/opensearch-project/OpenSearch/issues/4090), including bringing CCR as a plugin in the core. Could we combine this effort with Migrations to build primary cluster response as a configurable extension or component to CCR? This way the CCR plugin could be used to setup a "shadow cluster" (in the same manner it sets up a "follower" cluster today)? Some nice properties of CCR include the security model (document or field level) already baked in (though it will need to be refactored to a core security module), users can define replication at the field level (providing the ability to down sample a shadow cluster on migration), and the experience is already largely defined and familiar to the OpenSearch users.

**Comment by sumobrian** [comment]
We have decided not to support this mechanism because it lacks the flexibility required for our migration and replication use cases. This approach is heavily dependent on the source version, making it unsuitable for migrating across a wide range of Elasticsearch versions, especially older or newer releases. Additionally, this method does not integrate well with alternative data stores or engines, limiting its applicability in diverse environments. Our goal is to provide a solution that can handle multi-version migrations and support more complex scenarios, which this feature cannot accommodate.
