### ISSUE TITLE
Migrate elasticsearch 7.10.2 PV to OpenSearch 5.2

### ISSUE THREAD

**Issue by virasana** [opensearch-project/opensearch-migrations#1039]
Hi All, 

Please could you advise how I would restore existing data.  I originally used the helm chart here: https://github.com/opensearch-project/helm-charts. 

Additionally, the source data is on elastic search 7.10.2.  I want to migrate to opensearch 5.2.

I am using a PV pointing to Azure disk.

I am thinking to scale down the master statefulset, stand up a new PV and recreate the PVC to point to the new PV.  

Hopefully, the upgrade from ElasticSearch to Opensearch will be automatic?

There are really two issues here.  1. Replace existing PVC.  2.  Upgrade from ElasticSearch to OpenSearch. 

Will this work? 

Many Thanks!

I now want to restore the master instances.

Many Thanks

**Comment by peternied** [comment]
@virasana Thanks for the questions.  Migrations is focused on copying data from an existing cluster onto a fresh cluster, checkout our wiki [1] on what the toolset offers.  The suggestions from @up2neck are great as well.  

Since this issue isn't a bug report or feature request I'm closing out this issue.  Please consider looking at the forums [2] or starting a discussion on our slack workspace [3].

- [1] https://github.com/opensearch-project/opensearch-migrations/wiki 
- [2] https://forum.opensearch.org/
- [3] https://opensearch.org/slack.html
