### ISSUE TITLE
[FEATURE] Elasticsearch 6.7 Support

### ISSUE THREAD

**Issue by lucasrollemberg** [opensearch-project/opensearch-migrations#1163]
Do you have any predictions about Elasticsearch 6.7 support for OpenSearch 2.14 or 1.3? 
I have a domain that is on version 6.7.

**Comment by sumobrian** [comment]
Hi @lucasrollemberg,

Elasticsearch 6.7 to OpenSearch 2.14 (or OpenSearch 1.3) should not be a problem because it is a minor version difference from 6.8, which we regularly test. I encourage you to perform a migration assessment before migrating to understand any breaking changes and/or differences when migrating from ES 6.7 to OS 1.3/2.14. Additionally, make sure to test before performing your production migration.

If you run into any issues with this migration path (or any others), please open an issue. [Here](https://github.com/opensearch-project/opensearch-migrations/wiki/Is-Migration-Assistant-Right-for-You%3F) is a questionnaire that will help with your assessment.

**Comment by sumobrian** [comment]
I am marking this issue closed since the original question was answered.
